# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(616, 506)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(6, 0, 573, 127))
        self.groupBox.setObjectName("groupBox")
        self.choice_geom_parameters_file = QtWidgets.QRadioButton(self.groupBox)
        self.choice_geom_parameters_file.setGeometry(QtCore.QRect(12, 60, 119, 20))
        self.choice_geom_parameters_file.setObjectName("choice_geom_parameters_file")
        self.choice_vtk_file = QtWidgets.QRadioButton(self.groupBox)
        self.choice_vtk_file.setGeometry(QtCore.QRect(12, 28, 100, 20))
        self.choice_vtk_file.setChecked(True)
        self.choice_vtk_file.setObjectName("choice_vtk_file")
        self.choice_auto = QtWidgets.QRadioButton(self.groupBox)
        self.choice_auto.setGeometry(QtCore.QRect(12, 94, 159, 20))
        self.choice_auto.setObjectName("choice_auto")
        self.open_vtk_file_button = QtWidgets.QPushButton(self.groupBox)
        self.open_vtk_file_button.setGeometry(QtCore.QRect(138, 20, 113, 32))
        self.open_vtk_file_button.setObjectName("open_vtk_file_button")
        self.input_geom_param_width = QtWidgets.QLineEdit(self.groupBox)
        self.input_geom_param_width.setGeometry(QtCore.QRect(298, 56, 45, 21))
        self.input_geom_param_width.setInputMask("")
        self.input_geom_param_width.setMaxLength(5)
        self.input_geom_param_width.setReadOnly(True)
        self.input_geom_param_width.setObjectName("input_geom_param_width")
        self.input_geom_param_height = QtWidgets.QLineEdit(self.groupBox)
        self.input_geom_param_height.setGeometry(QtCore.QRect(492, 56, 45, 21))
        self.input_geom_param_height.setInputMask("")
        self.input_geom_param_height.setMaxLength(5)
        self.input_geom_param_height.setReadOnly(True)
        self.input_geom_param_height.setObjectName("input_geom_param_height")
        self.input_geom_param_length = QtWidgets.QLineEdit(self.groupBox)
        self.input_geom_param_length.setGeometry(QtCore.QRect(396, 56, 45, 21))
        self.input_geom_param_length.setInputMask("")
        self.input_geom_param_length.setMaxLength(5)
        self.input_geom_param_length.setReadOnly(True)
        self.input_geom_param_length.setObjectName("input_geom_param_length")
        self.l_nm_1 = QtWidgets.QLabel(self.groupBox)
        self.l_nm_1.setGeometry(QtCore.QRect(540, 60, 19, 16))
        self.l_nm_1.setObjectName("l_nm_1")
        self.open_geom_parameters_file_button = QtWidgets.QPushButton(self.groupBox)
        self.open_geom_parameters_file_button.setGeometry(QtCore.QRect(138, 54, 113, 32))
        self.open_geom_parameters_file_button.setObjectName("open_geom_parameters_file_button")
        self.vtk_filename_display = QtWidgets.QLineEdit(self.groupBox)
        self.vtk_filename_display.setGeometry(QtCore.QRect(258, 24, 297, 21))
        self.vtk_filename_display.setReadOnly(True)
        self.vtk_filename_display.setObjectName("vtk_filename_display")
        self.l_width = QtWidgets.QLabel(self.groupBox)
        self.l_width.setEnabled(True)
        self.l_width.setGeometry(QtCore.QRect(258, 60, 41, 16))
        self.l_width.setObjectName("l_width")
        self.l_length = QtWidgets.QLabel(self.groupBox)
        self.l_length.setGeometry(QtCore.QRect(348, 60, 45, 16))
        self.l_length.setObjectName("l_length")
        self.l_height = QtWidgets.QLabel(self.groupBox)
        self.l_height.setGeometry(QtCore.QRect(446, 60, 45, 16))
        self.l_height.setObjectName("l_height")
        self.l_cell_size = QtWidgets.QLabel(self.groupBox)
        self.l_cell_size.setGeometry(QtCore.QRect(244, 96, 60, 16))
        self.l_cell_size.setObjectName("l_cell_size")
        self.input_cell_size = QtWidgets.QLineEdit(self.groupBox)
        self.input_cell_size.setGeometry(QtCore.QRect(298, 92, 45, 21))
        self.input_cell_size.setInputMask("")
        self.input_cell_size.setMaxLength(4)
        self.input_cell_size.setReadOnly(True)
        self.input_cell_size.setObjectName("input_cell_size")
        self.l_nm_2 = QtWidgets.QLabel(self.groupBox)
        self.l_nm_2.setGeometry(QtCore.QRect(346, 96, 19, 16))
        self.l_nm_2.setObjectName("l_nm_2")
        self.l_nm_3 = QtWidgets.QLabel(self.groupBox)
        self.l_nm_3.setGeometry(QtCore.QRect(540, 94, 19, 16))
        self.l_nm_3.setObjectName("l_nm_3")
        self.input_substrate_height = QtWidgets.QLineEdit(self.groupBox)
        self.input_substrate_height.setGeometry(QtCore.QRect(492, 92, 45, 21))
        self.input_substrate_height.setInputMask("")
        self.input_substrate_height.setMaxLength(4)
        self.input_substrate_height.setObjectName("input_substrate_height")
        self.l_substrate_height = QtWidgets.QLabel(self.groupBox)
        self.l_substrate_height.setGeometry(QtCore.QRect(382, 96, 105, 16))
        self.l_substrate_height.setObjectName("l_substrate_height")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(8, 134, 573, 127))
        self.groupBox_2.setObjectName("groupBox_2")
        self.choice_stream_file = QtWidgets.QRadioButton(self.groupBox_2)
        self.choice_stream_file.setGeometry(QtCore.QRect(12, 94, 119, 20))
        self.choice_stream_file.setObjectName("choice_stream_file")
        self.choice_simple_pattern = QtWidgets.QRadioButton(self.groupBox_2)
        self.choice_simple_pattern.setGeometry(QtCore.QRect(12, 28, 115, 20))
        self.choice_simple_pattern.setChecked(True)
        self.choice_simple_pattern.setObjectName("choice_simple_pattern")
        self.open_stream_file_button = QtWidgets.QPushButton(self.groupBox_2)
        self.open_stream_file_button.setEnabled(False)
        self.open_stream_file_button.setGeometry(QtCore.QRect(138, 88, 113, 32))
        self.open_stream_file_button.setObjectName("open_stream_file_button")
        self.input_param2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.input_param2.setGeometry(QtCore.QRect(442, 24, 43, 21))
        self.input_param2.setMaxLength(4)
        self.input_param2.setObjectName("input_param2")
        self.pattern_selection = QtWidgets.QComboBox(self.groupBox_2)
        self.pattern_selection.setGeometry(QtCore.QRect(144, 24, 119, 26))
        self.pattern_selection.setObjectName("pattern_selection")
        self.pattern_selection.addItem("")
        self.pattern_selection.addItem("")
        self.pattern_selection.addItem("")
        self.pattern_selection.addItem("")
        self.pattern_selection.addItem("")
        self.l_param1 = QtWidgets.QLabel(self.groupBox_2)
        self.l_param1.setGeometry(QtCore.QRect(270, 28, 37, 16))
        self.l_param1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_param1.setObjectName("l_param1")
        self.input_param1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.input_param1.setGeometry(QtCore.QRect(318, 24, 45, 21))
        self.input_param1.setMaxLength(4)
        self.input_param1.setObjectName("input_param1")
        self.l_param2 = QtWidgets.QLabel(self.groupBox_2)
        self.l_param2.setGeometry(QtCore.QRect(392, 28, 41, 16))
        self.l_param2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l_param2.setAutoFillBackground(False)
        self.l_param2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_param2.setObjectName("l_param2")
        self.stream_file_filename_display = QtWidgets.QLineEdit(self.groupBox_2)
        self.stream_file_filename_display.setEnabled(False)
        self.stream_file_filename_display.setGeometry(QtCore.QRect(262, 92, 297, 21))
        self.stream_file_filename_display.setReadOnly(True)
        self.stream_file_filename_display.setObjectName("stream_file_filename_display")
        self.input_dwell_time = QtWidgets.QLineEdit(self.groupBox_2)
        self.input_dwell_time.setGeometry(QtCore.QRect(94, 58, 43, 21))
        self.input_dwell_time.setMaxLength(4)
        self.input_dwell_time.setObjectName("input_dwell_time")
        self.l_dwell_time = QtWidgets.QLabel(self.groupBox_2)
        self.l_dwell_time.setGeometry(QtCore.QRect(24, 62, 71, 16))
        self.l_dwell_time.setObjectName("l_dwell_time")
        self.l_pitch = QtWidgets.QLabel(self.groupBox_2)
        self.l_pitch.setGeometry(QtCore.QRect(178, 62, 39, 16))
        self.l_pitch.setObjectName("l_pitch")
        self.input_pitch = QtWidgets.QLineEdit(self.groupBox_2)
        self.input_pitch.setGeometry(QtCore.QRect(216, 58, 43, 21))
        self.input_pitch.setMaxLength(3)
        self.input_pitch.setObjectName("input_pitch")
        self.l_repeats = QtWidgets.QLabel(self.groupBox_2)
        self.l_repeats.setGeometry(QtCore.QRect(308, 62, 57, 16))
        self.l_repeats.setObjectName("l_repeats")
        self.input_repeats = QtWidgets.QLineEdit(self.groupBox_2)
        self.input_repeats.setGeometry(QtCore.QRect(364, 58, 121, 21))
        self.input_repeats.setObjectName("input_repeats")
        self.l_nm_4 = QtWidgets.QLabel(self.groupBox_2)
        self.l_nm_4.setGeometry(QtCore.QRect(366, 28, 19, 16))
        self.l_nm_4.setObjectName("l_nm_4")
        self.l_nm_5 = QtWidgets.QLabel(self.groupBox_2)
        self.l_nm_5.setGeometry(QtCore.QRect(488, 28, 19, 16))
        self.l_nm_5.setObjectName("l_nm_5")
        self.l_nm_6 = QtWidgets.QLabel(self.groupBox_2)
        self.l_nm_6.setGeometry(QtCore.QRect(140, 60, 19, 16))
        self.l_nm_6.setObjectName("l_nm_6")
        self.l_nm_7 = QtWidgets.QLabel(self.groupBox_2)
        self.l_nm_7.setGeometry(QtCore.QRect(264, 60, 19, 16))
        self.l_nm_7.setObjectName("l_nm_7")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(6, 270, 573, 93))
        self.groupBox_4.setObjectName("groupBox_4")
        self.open_beam_parameters_file_button = QtWidgets.QPushButton(self.groupBox_4)
        self.open_beam_parameters_file_button.setGeometry(QtCore.QRect(158, 20, 113, 32))
        self.open_beam_parameters_file_button.setObjectName("open_beam_parameters_file_button")
        self.open_precursor_parameters_file_button = QtWidgets.QPushButton(self.groupBox_4)
        self.open_precursor_parameters_file_button.setGeometry(QtCore.QRect(158, 54, 113, 32))
        self.open_precursor_parameters_file_button.setObjectName("open_precursor_parameters_file_button")
        self.beam_parameters_filename_display = QtWidgets.QLineEdit(self.groupBox_4)
        self.beam_parameters_filename_display.setGeometry(QtCore.QRect(280, 24, 275, 21))
        self.beam_parameters_filename_display.setReadOnly(True)
        self.beam_parameters_filename_display.setObjectName("beam_parameters_filename_display")
        self.precursor_parameters_filename_display = QtWidgets.QLineEdit(self.groupBox_4)
        self.precursor_parameters_filename_display.setGeometry(QtCore.QRect(280, 56, 275, 21))
        self.precursor_parameters_filename_display.setReadOnly(True)
        self.precursor_parameters_filename_display.setObjectName("precursor_parameters_filename_display")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(8, 30, 117, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(8, 62, 143, 16))
        self.label_13.setObjectName("label_13")
        self.start_febid_button = QtWidgets.QPushButton(self.tab)
        self.start_febid_button.setGeometry(QtCore.QRect(244, 374, 113, 45))
        self.start_febid_button.setObjectName("start_febid_button")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(6, 0, 573, 127))
        self.groupBox_3.setObjectName("groupBox_3")
        self.choice_geom_parameters_file_mc = QtWidgets.QRadioButton(self.groupBox_3)
        self.choice_geom_parameters_file_mc.setGeometry(QtCore.QRect(12, 60, 119, 20))
        self.choice_geom_parameters_file_mc.setObjectName("choice_geom_parameters_file_mc")
        self.choice_vtk_file_mc = QtWidgets.QRadioButton(self.groupBox_3)
        self.choice_vtk_file_mc.setGeometry(QtCore.QRect(12, 28, 100, 20))
        self.choice_vtk_file_mc.setChecked(True)
        self.choice_vtk_file_mc.setObjectName("choice_vtk_file_mc")
        self.open_vtk_file_button_mc = QtWidgets.QPushButton(self.groupBox_3)
        self.open_vtk_file_button_mc.setGeometry(QtCore.QRect(138, 20, 113, 32))
        self.open_vtk_file_button_mc.setObjectName("open_vtk_file_button_mc")
        self.input_geom_param_width_mc = QtWidgets.QLineEdit(self.groupBox_3)
        self.input_geom_param_width_mc.setGeometry(QtCore.QRect(296, 56, 45, 21))
        self.input_geom_param_width_mc.setInputMask("")
        self.input_geom_param_width_mc.setMaxLength(5)
        self.input_geom_param_width_mc.setObjectName("input_geom_param_width_mc")
        self.input_geom_param_height_mc = QtWidgets.QLineEdit(self.groupBox_3)
        self.input_geom_param_height_mc.setGeometry(QtCore.QRect(488, 56, 45, 21))
        self.input_geom_param_height_mc.setInputMask("")
        self.input_geom_param_height_mc.setMaxLength(5)
        self.input_geom_param_height_mc.setObjectName("input_geom_param_height_mc")
        self.input_geom_param_length_mc = QtWidgets.QLineEdit(self.groupBox_3)
        self.input_geom_param_length_mc.setGeometry(QtCore.QRect(392, 56, 45, 21))
        self.input_geom_param_length_mc.setInputMask("")
        self.input_geom_param_length_mc.setMaxLength(5)
        self.input_geom_param_length_mc.setObjectName("input_geom_param_length_mc")
        self.l_nm_1_mc = QtWidgets.QLabel(self.groupBox_3)
        self.l_nm_1_mc.setGeometry(QtCore.QRect(540, 60, 19, 16))
        self.l_nm_1_mc.setObjectName("l_nm_1_mc")
        self.open_geom_parameters_file_button_mc = QtWidgets.QPushButton(self.groupBox_3)
        self.open_geom_parameters_file_button_mc.setGeometry(QtCore.QRect(138, 54, 113, 32))
        self.open_geom_parameters_file_button_mc.setObjectName("open_geom_parameters_file_button_mc")
        self.vtk_filename_display_mc = QtWidgets.QLineEdit(self.groupBox_3)
        self.vtk_filename_display_mc.setGeometry(QtCore.QRect(258, 24, 297, 21))
        self.vtk_filename_display_mc.setReadOnly(True)
        self.vtk_filename_display_mc.setObjectName("vtk_filename_display_mc")
        self.l_width_mc = QtWidgets.QLabel(self.groupBox_3)
        self.l_width_mc.setGeometry(QtCore.QRect(258, 60, 37, 16))
        self.l_width_mc.setObjectName("l_width_mc")
        self.l_length_mc = QtWidgets.QLabel(self.groupBox_3)
        self.l_length_mc.setGeometry(QtCore.QRect(348, 60, 41, 16))
        self.l_length_mc.setObjectName("l_length_mc")
        self.l_height_mc = QtWidgets.QLabel(self.groupBox_3)
        self.l_height_mc.setGeometry(QtCore.QRect(446, 60, 41, 16))
        self.l_height_mc.setObjectName("l_height_mc")
        self.l_cell_size_mc = QtWidgets.QLabel(self.groupBox_3)
        self.l_cell_size_mc.setGeometry(QtCore.QRect(18, 96, 60, 16))
        self.l_cell_size_mc.setObjectName("l_cell_size_mc")
        self.input_cell_size_mc = QtWidgets.QLineEdit(self.groupBox_3)
        self.input_cell_size_mc.setGeometry(QtCore.QRect(78, 92, 45, 21))
        self.input_cell_size_mc.setInputMask("")
        self.input_cell_size_mc.setText("")
        self.input_cell_size_mc.setMaxLength(4)
        self.input_cell_size_mc.setObjectName("input_cell_size_mc")
        self.l_nm_2_mc = QtWidgets.QLabel(self.groupBox_3)
        self.l_nm_2_mc.setGeometry(QtCore.QRect(126, 96, 19, 16))
        self.l_nm_2_mc.setObjectName("l_nm_2_mc")
        self.l_substrate_height_mc = QtWidgets.QLabel(self.groupBox_3)
        self.l_substrate_height_mc.setGeometry(QtCore.QRect(170, 96, 105, 16))
        self.l_substrate_height_mc.setObjectName("l_substrate_height_mc")
        self.input_substrate_height_mc = QtWidgets.QLineEdit(self.groupBox_3)
        self.input_substrate_height_mc.setGeometry(QtCore.QRect(280, 92, 45, 21))
        self.input_substrate_height_mc.setInputMask("")
        self.input_substrate_height_mc.setMaxLength(4)
        self.input_substrate_height_mc.setObjectName("input_substrate_height_mc")
        self.l_nm_3_mc = QtWidgets.QLabel(self.groupBox_3)
        self.l_nm_3_mc.setGeometry(QtCore.QRect(328, 96, 19, 16))
        self.l_nm_3_mc.setObjectName("l_nm_3_mc")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(6, 134, 573, 153))
        self.groupBox_5.setObjectName("groupBox_5")
        self.energy_cutoff = QtWidgets.QLineEdit(self.groupBox_5)
        self.energy_cutoff.setGeometry(QtCore.QRect(58, 90, 45, 21))
        self.energy_cutoff.setInputMask("")
        self.energy_cutoff.setText("")
        self.energy_cutoff.setMaxLength(3)
        self.energy_cutoff.setObjectName("energy_cutoff")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(32, 70, 25, 16))
        self.label_17.setObjectName("label_17")
        self.beam_energy = QtWidgets.QLineEdit(self.groupBox_5)
        self.beam_energy.setGeometry(QtCore.QRect(58, 66, 45, 21))
        self.beam_energy.setInputMask("")
        self.beam_energy.setText("")
        self.beam_energy.setMaxLength(4)
        self.beam_energy.setObjectName("beam_energy")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(20, 94, 41, 16))
        self.label_18.setObjectName("label_18")
        self.beam_parameters_filename_display_mc = QtWidgets.QLineEdit(self.groupBox_5)
        self.beam_parameters_filename_display_mc.setGeometry(QtCore.QRect(142, 28, 415, 21))
        self.beam_parameters_filename_display_mc.setReadOnly(True)
        self.beam_parameters_filename_display_mc.setObjectName("beam_parameters_filename_display_mc")
        self.open_beam_parameters_file_button_mc = QtWidgets.QPushButton(self.groupBox_5)
        self.open_beam_parameters_file_button_mc.setGeometry(QtCore.QRect(12, 24, 113, 32))
        self.open_beam_parameters_file_button_mc.setObjectName("open_beam_parameters_file_button_mc")
        self.number_of_e = QtWidgets.QLineEdit(self.groupBox_5)
        self.number_of_e.setGeometry(QtCore.QRect(58, 114, 45, 21))
        self.number_of_e.setInputMask("")
        self.number_of_e.setText("")
        self.number_of_e.setMaxLength(4)
        self.number_of_e.setObjectName("number_of_e")
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(40, 118, 15, 16))
        self.label_21.setObjectName("label_21")
        self.gauss_dev = QtWidgets.QLineEdit(self.groupBox_5)
        self.gauss_dev.setGeometry(QtCore.QRect(292, 64, 45, 21))
        self.gauss_dev.setInputMask("")
        self.gauss_dev.setText("")
        self.gauss_dev.setMaxLength(4)
        self.gauss_dev.setObjectName("gauss_dev")
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setGeometry(QtCore.QRect(166, 68, 123, 16))
        self.label_22.setObjectName("label_22")
        self.x_pos = QtWidgets.QLineEdit(self.groupBox_5)
        self.x_pos.setGeometry(QtCore.QRect(292, 88, 45, 21))
        self.x_pos.setInputMask("")
        self.x_pos.setText("")
        self.x_pos.setMaxLength(4)
        self.x_pos.setObjectName("x_pos")
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setGeometry(QtCore.QRect(268, 92, 21, 16))
        self.label_23.setObjectName("label_23")
        self.y_pos = QtWidgets.QLineEdit(self.groupBox_5)
        self.y_pos.setGeometry(QtCore.QRect(292, 112, 45, 21))
        self.y_pos.setInputMask("")
        self.y_pos.setText("")
        self.y_pos.setMaxLength(4)
        self.y_pos.setObjectName("y_pos")
        self.label_25 = QtWidgets.QLabel(self.groupBox_5)
        self.label_25.setGeometry(QtCore.QRect(268, 116, 21, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setGeometry(QtCore.QRect(108, 68, 25, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        self.label_27.setGeometry(QtCore.QRect(108, 92, 25, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_5)
        self.label_28.setGeometry(QtCore.QRect(342, 90, 25, 16))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(342, 114, 25, 16))
        self.label_29.setObjectName("label_29")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(6, 296, 573, 55))
        self.groupBox_6.setObjectName("groupBox_6")
        self.open_precursor_parameters_file_button_mc = QtWidgets.QPushButton(self.groupBox_6)
        self.open_precursor_parameters_file_button_mc.setGeometry(QtCore.QRect(158, 20, 113, 32))
        self.open_precursor_parameters_file_button_mc.setObjectName("open_precursor_parameters_file_button_mc")
        self.precursor_parameters_filename_display_mc = QtWidgets.QLineEdit(self.groupBox_6)
        self.precursor_parameters_filename_display_mc.setGeometry(QtCore.QRect(280, 24, 275, 21))
        self.precursor_parameters_filename_display_mc.setReadOnly(True)
        self.precursor_parameters_filename_display_mc.setObjectName("precursor_parameters_filename_display_mc")
        self.label_24 = QtWidgets.QLabel(self.groupBox_6)
        self.label_24.setGeometry(QtCore.QRect(8, 28, 143, 16))
        self.label_24.setObjectName("label_24")
        self.start_mc_button = QtWidgets.QPushButton(self.tab_2)
        self.start_mc_button.setGeometry(QtCore.QRect(244, 368, 113, 45))
        self.start_mc_button.setObjectName("start_mc_button")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 616, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen_session = QtWidgets.QAction(MainWindow)
        self.actionOpen_session.setObjectName("actionOpen_session")
        self.actionManual = QtWidgets.QAction(MainWindow)
        self.actionManual.setObjectName("actionManual")
        self.menuFile.addAction(self.actionOpen_session)
        self.menuFile.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionManual)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pattern_selection.setCurrentIndex(0)
        self.choice_vtk_file.clicked.connect(MainWindow.vtk_chosen)
        self.choice_geom_parameters_file.clicked.connect(MainWindow.geom_parameters_chosen)
        self.choice_auto.clicked.connect(MainWindow.auto_chosen)
        self.choice_simple_pattern.clicked.connect(MainWindow.simple_pattern_chosen)
        self.choice_stream_file.clicked.connect(MainWindow.stream_file_chosen)
        self.open_vtk_file_button.clicked.connect(MainWindow.open_vtk_file)
        self.open_geom_parameters_file_button.clicked.connect(MainWindow.open_geom_parameters_file)
        self.open_stream_file_button.clicked.connect(MainWindow.open_stream_file)
        self.open_beam_parameters_file_button.clicked.connect(MainWindow.open_beam_parameters_file)
        self.open_precursor_parameters_file_button.clicked.connect(MainWindow.open_precursor_parameters_file)
        self.open_vtk_file_button_mc.clicked.connect(MainWindow.open_vtk_file)
        self.choice_vtk_file_mc.clicked.connect(MainWindow.vtk_chosen)
        self.choice_geom_parameters_file_mc.clicked.connect(MainWindow.geom_parameters_chosen)
        self.open_beam_parameters_file_button_mc.clicked.connect(MainWindow.open_beam_parameters_file)
        self.open_precursor_parameters_file_button_mc.clicked.connect(MainWindow.open_precursor_parameters_file)
        self.open_geom_parameters_file_button_mc.clicked.connect(MainWindow.open_geom_parameters_file)
        self.pattern_selection.currentIndexChanged['int'].connect(MainWindow.pattern_selection_changed)
        self.start_mc_button.clicked.connect(MainWindow.start_mc)
        self.start_febid_button.clicked.connect(MainWindow.start_febid)
        self.input_geom_param_width.editingFinished.connect(MainWindow.check_input)
        self.input_geom_param_length.editingFinished.connect(MainWindow.check_input)
        self.input_geom_param_height.editingFinished.connect(MainWindow.check_input)
        self.input_cell_size.editingFinished.connect(MainWindow.check_input)
        self.input_substrate_height.editingFinished.connect(MainWindow.check_input)
        self.input_param2.editingFinished.connect(MainWindow.check_input)
        self.input_param1.editingFinished.connect(MainWindow.check_input)
        self.input_geom_param_width_mc.editingFinished.connect(MainWindow.check_input)
        self.input_geom_param_length_mc.editingFinished.connect(MainWindow.check_input)
        self.input_geom_param_height_mc.editingFinished.connect(MainWindow.check_input)
        self.input_cell_size_mc.editingFinished.connect(MainWindow.check_input)
        self.input_substrate_height_mc.editingFinished.connect(MainWindow.check_input)
        self.beam_energy.editingFinished.connect(MainWindow.check_input)
        self.energy_cutoff.editingFinished.connect(MainWindow.check_input)
        self.number_of_e.editingFinished.connect(MainWindow.check_input)
        self.gauss_dev.editingFinished.connect(MainWindow.check_input)
        self.x_pos.editingFinished.connect(MainWindow.check_input)
        self.y_pos.editingFinished.connect(MainWindow.check_input)
        self.input_dwell_time.editingFinished.connect(MainWindow.check_input)
        self.input_pitch.editingFinished.connect(MainWindow.check_input)
        self.input_repeats.editingFinished.connect(MainWindow.check_input)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Initial conditions"))
        self.choice_geom_parameters_file.setText(_translate("MainWindow", "Parameters"))
        self.choice_vtk_file.setText(_translate("MainWindow", "VTK file"))
        self.choice_auto.setText(_translate("MainWindow", "Auto (from streamfile)"))
        self.open_vtk_file_button.setText(_translate("MainWindow", "Open file"))
        self.input_geom_param_width.setText(_translate("MainWindow", "200"))
        self.input_geom_param_width.setPlaceholderText(_translate("MainWindow", "200"))
        self.input_geom_param_height.setText(_translate("MainWindow", "400"))
        self.input_geom_param_height.setPlaceholderText(_translate("MainWindow", "400"))
        self.input_geom_param_length.setText(_translate("MainWindow", "200"))
        self.input_geom_param_length.setPlaceholderText(_translate("MainWindow", "200"))
        self.l_nm_1.setText(_translate("MainWindow", "nm"))
        self.open_geom_parameters_file_button.setText(_translate("MainWindow", "Open file"))
        self.vtk_filename_display.setPlaceholderText(_translate("MainWindow", "Select file..."))
        self.l_width.setText(_translate("MainWindow", "Width:"))
        self.l_length.setText(_translate("MainWindow", "Length:"))
        self.l_height.setText(_translate("MainWindow", "Height:"))
        self.l_cell_size.setText(_translate("MainWindow", "Cell size:"))
        self.input_cell_size.setText(_translate("MainWindow", "2"))
        self.input_cell_size.setPlaceholderText(_translate("MainWindow", "2"))
        self.l_nm_2.setText(_translate("MainWindow", "nm"))
        self.l_nm_3.setText(_translate("MainWindow", "nm"))
        self.input_substrate_height.setText(_translate("MainWindow", "8"))
        self.input_substrate_height.setPlaceholderText(_translate("MainWindow", "4"))
        self.l_substrate_height.setText(_translate("MainWindow", "Substrate height:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Pattern"))
        self.choice_stream_file.setText(_translate("MainWindow", "Stream file"))
        self.choice_simple_pattern.setText(_translate("MainWindow", "Simple pattern"))
        self.open_stream_file_button.setText(_translate("MainWindow", "Open file"))
        self.input_param2.setText(_translate("MainWindow", "100"))
        self.input_param2.setPlaceholderText(_translate("MainWindow", "100"))
        self.pattern_selection.setItemText(0, _translate("MainWindow", "Point"))
        self.pattern_selection.setItemText(1, _translate("MainWindow", "Rectangle"))
        self.pattern_selection.setItemText(2, _translate("MainWindow", "Square"))
        self.pattern_selection.setItemText(3, _translate("MainWindow", "Triangle (equilateral)"))
        self.pattern_selection.setItemText(4, _translate("MainWindow", "Circle"))
        self.l_param1.setText(_translate("MainWindow", "x:"))
        self.input_param1.setText(_translate("MainWindow", "100"))
        self.input_param1.setPlaceholderText(_translate("MainWindow", "100"))
        self.l_param2.setText(_translate("MainWindow", "y:"))
        self.stream_file_filename_display.setPlaceholderText(_translate("MainWindow", "Select file..."))
        self.input_dwell_time.setText(_translate("MainWindow", "100"))
        self.input_dwell_time.setPlaceholderText(_translate("MainWindow", "100"))
        self.l_dwell_time.setText(_translate("MainWindow", "Dwell time:"))
        self.l_pitch.setText(_translate("MainWindow", "Pitch:"))
        self.input_pitch.setText(_translate("MainWindow", "1"))
        self.input_pitch.setPlaceholderText(_translate("MainWindow", "1"))
        self.l_repeats.setText(_translate("MainWindow", "Repeats:"))
        self.input_repeats.setText(_translate("MainWindow", "1000"))
        self.input_repeats.setPlaceholderText(_translate("MainWindow", "1000"))
        self.l_nm_4.setText(_translate("MainWindow", "nm"))
        self.l_nm_5.setText(_translate("MainWindow", "nm"))
        self.l_nm_6.setText(_translate("MainWindow", "µs"))
        self.l_nm_7.setText(_translate("MainWindow", "nm"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Beam and precursor"))
        self.open_beam_parameters_file_button.setText(_translate("MainWindow", "Open file"))
        self.open_precursor_parameters_file_button.setText(_translate("MainWindow", "Open file"))
        self.beam_parameters_filename_display.setPlaceholderText(_translate("MainWindow", "Select file..."))
        self.precursor_parameters_filename_display.setPlaceholderText(_translate("MainWindow", "Select file..."))
        self.label_12.setText(_translate("MainWindow", "Beam parameters"))
        self.label_13.setText(_translate("MainWindow", "Precursor parameters"))
        self.start_febid_button.setText(_translate("MainWindow", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "FEBID"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Initial conditions"))
        self.choice_geom_parameters_file_mc.setText(_translate("MainWindow", "Parameters"))
        self.choice_vtk_file_mc.setText(_translate("MainWindow", "VTK file"))
        self.open_vtk_file_button_mc.setText(_translate("MainWindow", "Open file"))
        self.input_geom_param_width_mc.setPlaceholderText(_translate("MainWindow", "200"))
        self.input_geom_param_height_mc.setPlaceholderText(_translate("MainWindow", "400"))
        self.input_geom_param_length_mc.setPlaceholderText(_translate("MainWindow", "200"))
        self.l_nm_1_mc.setText(_translate("MainWindow", "nm"))
        self.open_geom_parameters_file_button_mc.setText(_translate("MainWindow", "Open file"))
        self.vtk_filename_display_mc.setPlaceholderText(_translate("MainWindow", "Select file..."))
        self.l_width_mc.setText(_translate("MainWindow", "width"))
        self.l_length_mc.setText(_translate("MainWindow", "length"))
        self.l_height_mc.setText(_translate("MainWindow", "height"))
        self.l_cell_size_mc.setText(_translate("MainWindow", "Cell size:"))
        self.input_cell_size_mc.setPlaceholderText(_translate("MainWindow", "2"))
        self.l_nm_2_mc.setText(_translate("MainWindow", "nm"))
        self.l_substrate_height_mc.setText(_translate("MainWindow", "Substrate height:"))
        self.input_substrate_height_mc.setPlaceholderText(_translate("MainWindow", "4"))
        self.l_nm_3_mc.setText(_translate("MainWindow", "nm"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Beam parameters"))
        self.energy_cutoff.setPlaceholderText(_translate("MainWindow", "0.1"))
        self.label_17.setText(_translate("MainWindow", "E0:"))
        self.beam_energy.setPlaceholderText(_translate("MainWindow", "20.0"))
        self.label_18.setText(_translate("MainWindow", "Emin:"))
        self.beam_parameters_filename_display_mc.setPlaceholderText(_translate("MainWindow", "Select file..."))
        self.open_beam_parameters_file_button_mc.setText(_translate("MainWindow", "Open file"))
        self.number_of_e.setPlaceholderText(_translate("MainWindow", "100"))
        self.label_21.setText(_translate("MainWindow", "N:"))
        self.gauss_dev.setPlaceholderText(_translate("MainWindow", "5"))
        self.label_22.setText(_translate("MainWindow", "Gaussian deviation:"))
        self.x_pos.setPlaceholderText(_translate("MainWindow", "100"))
        self.label_23.setText(_translate("MainWindow", "x:"))
        self.y_pos.setPlaceholderText(_translate("MainWindow", "100"))
        self.label_25.setText(_translate("MainWindow", "y:"))
        self.label_26.setText(_translate("MainWindow", "keV"))
        self.label_27.setText(_translate("MainWindow", "keV"))
        self.label_28.setText(_translate("MainWindow", "nm"))
        self.label_29.setText(_translate("MainWindow", "nm"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Beam and precursor"))
        self.open_precursor_parameters_file_button_mc.setText(_translate("MainWindow", "Open file"))
        self.precursor_parameters_filename_display_mc.setPlaceholderText(_translate("MainWindow", "Select file..."))
        self.label_24.setText(_translate("MainWindow", "Precursor parameters"))
        self.start_mc_button.setText(_translate("MainWindow", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Monte Carlo"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionOpen_session.setText(_translate("MainWindow", "Open session"))
        self.actionManual.setText(_translate("MainWindow", "Manual"))

